version: "3"
services:
  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - "./:/var/www/html"
      - "./docker/site.conf:/etc/nginx/conf.d/default.conf"
    links:
      - mysql
  php:
    build:
      context: .
    volumes:
      - "./:/var/www/html"
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - mysql
  mysql:
    build:
        context: ./docker/mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'Testing'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
