version: "3"
services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"
      - "./docker/site.conf:/etc/nginx/conf.d/default.conf"
    links:
      - mysql
  php:
    build:
      context: .
    volumes:
      - "./:/var/www/html"
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - mysql
  mysql:
    build:
        context: ./docker/mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'micbd'
      MYSQL_USER: 'mic'
      MYSQL_PASSWORD: '2627376jfk!@#'
      MYSQL_ROOT_PASSWORD: '2627376jfk!@#'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 9999:80
volumes:
  dbdata:
